### ISSUE TITLE
영상 업로드 로직 변경(presigned url 발행 후 저장 방식)

### ISSUE THREAD

**Issue by Bellroute** [Collusic/climingo-api#91]
# AS-IS
- File 객체를 api로 전달
- 서버에서 File 객체로 s3 업로드
- 썸네일 추출
- 썸네일 File s3로 업로드

# To-Be
- presignedUrl api 호출 (fileName, extension 전달)
- 서버에서 presignedUrl 응답
- 클라이언트에서 presignedUrl로 s3 업로드
- 기록생성 api 호출
- 서버에서 db 저장
- s3 저장된 영상으로 썸네일 추출
- 서버에서 썸네일 s3에 업로드 후 경로 db에 저장

# To-Do
- [x] presignedUrl 생성 url 명세 작성
- [x] 기록 생성 url 명세 수정
- [x] presignedUrl 생성 api 구현
- [x] 기록 생성 api 로직 수정
